services:
  clickhouse-01:
    image: "clickhouse/clickhouse-server:${CHVER:-latest}"
    user: "1000:1000"
    container_name: clickhouse-01
    hostname: clickhouse-01
    restart: unless-stopped
    volumes:
      - ${PWD}/fs/volumes/clickhouse-01/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse-01/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/fs/volumes/clickhouse-01/var/log/clickhouse-server:/var/log/clickhouse-server/
      - ${PWD}/fs/volumes/clickhouse-01/var/lib/clickhouse:/var/lib/clickhouse/
      - ${PWD}/data:/var/lib/clickhouse/user_files/data/
    ports:
      - "8123:8123"
      - "9000:9000"
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03
  clickhouse-02:
    image: "clickhouse/clickhouse-server:${CHVER:-latest}"
    user: "1000:1000"
    container_name: clickhouse-02
    hostname: clickhouse-02
    restart: unless-stopped
    volumes:
      - ${PWD}/fs/volumes/clickhouse-02/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse-02/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/fs/volumes/clickhouse-02/var/log/clickhouse-server:/var/log/clickhouse-server/
      - ${PWD}/fs/volumes/clickhouse-02/var/lib/clickhouse:/var/lib/clickhouse/
      - ${PWD}/data:/var/lib/clickhouse/user_files/data/
    ports:
      - "8124:8123"
      - "9001:9000"
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03
  clickhouse-keeper-01:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    user: "1000:1000"
    container_name: clickhouse-keeper-01
    hostname: clickhouse-keeper-01
    restart: unless-stopped
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-01/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
      - ${PWD}/fs/volumes/clickhouse-keeper-01/var/log/clickhouse-keeper:/var/log/clickhouse-server/
      - ${PWD}/fs/volumes/clickhouse-keeper-01/var/lib/clickhouse-keeper:/var/lib/clickhouse-keeper/
      - ${PWD}/fs/volumes/clickhouse-keeper-01/var/lib/clickhouse:/var/lib/clickhouse/
    ports:
      - "9181:9181"
  clickhouse-keeper-02:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    user: "1000:1000"
    container_name: clickhouse-keeper-02
    hostname: clickhouse-keeper-02
    restart: unless-stopped
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-02/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
      - ${PWD}/fs/volumes/clickhouse-keeper-02/var/log/clickhouse-keeper:/var/log/clickhouse-server/
      - ${PWD}/fs/volumes/clickhouse-keeper-02/var/lib/clickhouse-keeper:/var/lib/clickhouse-keeper/
      - ${PWD}/fs/volumes/clickhouse-keeper-02/var/lib/clickhouse:/var/lib/clickhouse/
    ports:
      - "9182:9181"
  clickhouse-keeper-03:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    user: "1000:1000"
    container_name: clickhouse-keeper-03
    hostname: clickhouse-keeper-03
    restart: unless-stopped
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-03/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
      - ${PWD}/fs/volumes/clickhouse-keeper-03/var/log/clickhouse-keeper:/var/log/clickhouse-server/
      - ${PWD}/fs/volumes/clickhouse-keeper-03/var/lib/clickhouse-keeper:/var/lib/clickhouse-keeper/
      - ${PWD}/fs/volumes/clickhouse-keeper-03/var/lib/clickhouse:/var/lib/clickhouse/
    ports:
      - "9183:9181"
  metabase:
    image: "metabase/metabase:${MB_VER:-latest}"
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      MB_DB_TYPE: "postgres"
      MB_DB_DBNAME: "${MB_DB_DBNAME}"
      MB_DB_PORT: ${MB_DB_PORT}
      MB_DB_USER: "${MB_DB_USER}"
      MB_DB_PASS: "${MB_DB_PASS}"
      MB_DB_HOST: "postgres"
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  postgres:
    image: "postgres:${PGVER:-latest}"
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_DB: "${PGDB:-postgres}"
      POSTGRES_USER: "${PGUSER:-postgres}"
      POSTGRES_PASSWORD: "${PGPASS:-postgres}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
volumes:
  pg-data:
