services:
  clickhouse-01:
    image: clickhouse/clickhouse-server:${CLICKHOUSE_VER:-latest}
    user: 1000:1000
    container_name: clickhouse-01
    hostname: clickhouse-01
    restart: unless-stopped
    volumes:
      - ${PWD}/fs/volumes/clickhouse-01/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse-01/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/fs/volumes/clickhouse-01/var/log/clickhouse-server:/var/log/clickhouse-server/
      - ${PWD}/fs/volumes/clickhouse-01/var/lib/clickhouse:/var/lib/clickhouse/
      - ${PWD}/data:/var/lib/clickhouse/user_files/data/
    ports:
      - 8123:8123
      - 9000:9000
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03
  clickhouse-02:
    image: clickhouse/clickhouse-server:${CLICKHOUSE_VER:-latest}
    user: 1000:1000
    container_name: clickhouse-02
    hostname: clickhouse-02
    restart: unless-stopped
    volumes:
      - ${PWD}/fs/volumes/clickhouse-02/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse-02/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/fs/volumes/clickhouse-02/var/log/clickhouse-server:/var/log/clickhouse-server/
      - ${PWD}/fs/volumes/clickhouse-02/var/lib/clickhouse:/var/lib/clickhouse/
      - ${PWD}/data:/var/lib/clickhouse/user_files/data/
    ports:
      - 8124:8123
      - 9001:9000
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03
  clickhouse-keeper-01:
    image: clickhouse/clickhouse-keeper:${CLICKHOUSE_KEEPER_VER:-latest-alpine}
    user: 1000:1000
    container_name: clickhouse-keeper-01
    hostname: clickhouse-keeper-01
    restart: unless-stopped
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-01/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
      - ${PWD}/fs/volumes/clickhouse-keeper-01/var/log/clickhouse-keeper:/var/log/clickhouse-server/
      - ${PWD}/fs/volumes/clickhouse-keeper-01/var/lib/clickhouse-keeper:/var/lib/clickhouse-keeper/
      - ${PWD}/fs/volumes/clickhouse-keeper-01/var/lib/clickhouse:/var/lib/clickhouse/
    ports:
      - 9181:9181
  clickhouse-keeper-02:
    image: clickhouse/clickhouse-keeper:${CLICKHOUSE_KEEPER_VER:-latest-alpine}
    user: 1000:1000
    container_name: clickhouse-keeper-02
    hostname: clickhouse-keeper-02
    restart: unless-stopped
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-02/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
      - ${PWD}/fs/volumes/clickhouse-keeper-02/var/log/clickhouse-keeper:/var/log/clickhouse-server/
      - ${PWD}/fs/volumes/clickhouse-keeper-02/var/lib/clickhouse-keeper:/var/lib/clickhouse-keeper/
      - ${PWD}/fs/volumes/clickhouse-keeper-02/var/lib/clickhouse:/var/lib/clickhouse/
    ports:
      - 9182:9181
  clickhouse-keeper-03:
    image: clickhouse/clickhouse-keeper:${CLICKHOUSE_KEEPER_VER:-latest-alpine}
    user: 1000:1000
    container_name: clickhouse-keeper-03
    hostname: clickhouse-keeper-03
    restart: unless-stopped
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-03/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
      - ${PWD}/fs/volumes/clickhouse-keeper-03/var/log/clickhouse-keeper:/var/log/clickhouse-server/
      - ${PWD}/fs/volumes/clickhouse-keeper-03/var/lib/clickhouse-keeper:/var/lib/clickhouse-keeper/
      - ${PWD}/fs/volumes/clickhouse-keeper-03/var/lib/clickhouse:/var/lib/clickhouse/
    ports:
      - 9183:9181
  metabase:
    image: metabase/metabase:${METABASE_VER:-latest}
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - ${METABASE_PORT}:3000
    depends_on:
      - postgres
    environment:
      MB_DB_TYPE: postgres
      MB_DB_HOST: ${POSTGRES_HOST}
      MB_DB_PORT: ${POSTGRES_PORT}
      MB_DB_DBNAME: ${METABASE_DB_NAME}
      MB_DB_USER: ${METABASE_DB_USER}
      MB_DB_PASS: ${METABASE_DB_PASS}
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  postgres:
    image: "postgres:${POSTGRES_VER:-latest}"
    container_name: postgres
    hostname: ${POSTGRES_HOST}
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      DAGSTER_DB_NAME: ${DAGSTER_DB_NAME}
      DAGSTER_DB_USER: ${DAGSTER_DB_USER}
      DAGSTER_DB_PASS: ${DAGSTER_DB_PASS}
      METABASE_DB_NAME: ${METABASE_DB_NAME}
      METABASE_DB_USER: ${METABASE_DB_USER}
      METABASE_DB_PASS: ${METABASE_DB_PASS}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 4G
volumes:
  pg-data:
# TODO: разобраться с правами на директории:
# назначение пользователя 1000:1000 приводит к невозможности запуска контейнеров из-за проблем с правами, 
# а при сохранении владельца 0:0 - к проблемам с доступом к директориям и созданию файлов от имени пользователя root
