services:
  clickhouse-01:
    image: "clickhouse/clickhouse-server:${CHVER:-latest}"
    user: "1000:1000"
    container_name: clickhouse-01
    hostname: clickhouse-01
    restart: unless-stopped
    volumes:
      - ${PWD}/fs/volumes/clickhouse-01/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse-01/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/fs/volumes/clickhouse-01/var/log/clickhouse-server:/var/log/clickhouse-server/
      - ${PWD}/fs/volumes/clickhouse-01/var/lib/clickhouse:/var/lib/clickhouse/
      - ${PWD}/data:/var/lib/clickhouse/user_files/data/
    ports:
      - "8123:8123"
      - "9000:9000"
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03
  clickhouse-02:
    image: "clickhouse/clickhouse-server:${CHVER:-latest}"
    user: "1000:1000"
    container_name: clickhouse-02
    hostname: clickhouse-02
    restart: unless-stopped
    volumes:
      - ${PWD}/fs/volumes/clickhouse-02/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse-02/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/fs/volumes/clickhouse-02/var/log/clickhouse-server:/var/log/clickhouse-server/
      - ${PWD}/fs/volumes/clickhouse-02/var/lib/clickhouse:/var/lib/clickhouse/
      - ${PWD}/data:/var/lib/clickhouse/user_files/data/
    ports:
      - "8124:8123"
      - "9001:9000"
    depends_on:
      - clickhouse-keeper-01
      - clickhouse-keeper-02
      - clickhouse-keeper-03
  clickhouse-keeper-01:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    user: "1000:1000"
    container_name: clickhouse-keeper-01
    hostname: clickhouse-keeper-01
    restart: unless-stopped
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-01/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
      - ${PWD}/fs/volumes/clickhouse-keeper-01/var/log/clickhouse-keeper:/var/log/clickhouse-server/
      - ${PWD}/fs/volumes/clickhouse-keeper-01/var/lib/clickhouse-keeper:/var/lib/clickhouse-keeper/
      - ${PWD}/fs/volumes/clickhouse-keeper-01/var/lib/clickhouse:/var/lib/clickhouse/
    ports:
      - "9181:9181"
  clickhouse-keeper-02:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    user: "1000:1000"
    container_name: clickhouse-keeper-02
    hostname: clickhouse-keeper-02
    restart: unless-stopped
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-02/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
      - ${PWD}/fs/volumes/clickhouse-keeper-02/var/log/clickhouse-keeper:/var/log/clickhouse-server/
      - ${PWD}/fs/volumes/clickhouse-keeper-02/var/lib/clickhouse-keeper:/var/lib/clickhouse-keeper/
      - ${PWD}/fs/volumes/clickhouse-keeper-02/var/lib/clickhouse:/var/lib/clickhouse/
    ports:
      - "9182:9181"
  clickhouse-keeper-03:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    user: "1000:1000"
    container_name: clickhouse-keeper-03
    hostname: clickhouse-keeper-03
    restart: unless-stopped
    volumes:
      - ${PWD}/fs/volumes/clickhouse-keeper-03/etc/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
      - ${PWD}/fs/volumes/clickhouse-keeper-03/var/log/clickhouse-keeper:/var/log/clickhouse-server/
      - ${PWD}/fs/volumes/clickhouse-keeper-03/var/lib/clickhouse-keeper:/var/lib/clickhouse-keeper/
      - ${PWD}/fs/volumes/clickhouse-keeper-03/var/lib/clickhouse:/var/lib/clickhouse/
    ports:
      - "9183:9181"
