#!/bin/bash
set -e

psql --username "$POSTGRES_USER" <<EOSQL
  CREATE USER "$DAGSTER_DB_USER" WITH ENCRYPTED PASSWORD '$DAGSTER_DB_PASS';
  CREATE DATABASE "$DAGSTER_DB_NAME" OWNER "$DAGSTER_DB_USER";
  CREATE USER "$METABASE_DB_USER" WITH ENCRYPTED PASSWORD '$METABASE_DB_PASS';
  CREATE DATABASE "$METABASE_DB_NAME" OWNER "$METABASE_DB_USER";
  CREATE USER "$DATA_DB_USER" WITH ENCRYPTED PASSWORD '$DATA_DB_PASS';
  CREATE DATABASE "$DATA_DB_NAME" OWNER "$DATA_DB_USER";
EOSQL

psql --username "$POSTGRES_USER" --dbname "$DATA_DB_NAME" <<EOSQL
  CREATE SCHEMA IF NOT EXISTS stage AUTHORIZATION "$DATA_DB_USER";
  CREATE SCHEMA IF NOT EXISTS data_vault AUTHORIZATION "$DATA_DB_USER";
EOSQL
